apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: file-standard
parameters:
  skuName: Standard_ZRS
provisioner: kubernetes.io/azure-file
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: false