{{ if .Values.replication }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: gcr.io/google_samples/gb-redisslave:v2
        resources:
          requests:
            cpu: 20m
            memory: 100Mi
        ports:
        - containerPort: 6379
{{ end }}
